/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatgptRouteImport } from './routes/chatgpt'
import { Route as IndexRouteImport } from './routes/index'

const ChatgptRoute = ChatgptRouteImport.update({
  id: '/chatgpt',
  path: '/chatgpt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chatgpt': typeof ChatgptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chatgpt': typeof ChatgptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chatgpt': typeof ChatgptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chatgpt'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chatgpt'
  id: '__root__' | '/' | '/chatgpt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatgptRoute: typeof ChatgptRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/chatgpt': {
      id: '/chatgpt'
      path: '/chatgpt'
      fullPath: '/chatgpt'
      preLoaderRoute: typeof ChatgptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatgptRoute: ChatgptRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
